Create transfer_file.yml
deNBI/fts3-databases-staging pull request #1
Opened 2023-04-20 14:04 UTC by qqmok

2023-04-20 14:17 UTC, dweinholz requested changes

2023-04-20 14:17 UTC, dweinholz commented on .github/workflows/transfer_file.yml
> +        default: path/filename.json
Can you change this to required and remove the default? 

A default does not make sense for this use case

2023-04-20 14:39 UTC, qqmok commented on .github/workflows/transfer_file.yml
> +        default: path/filename.json
Is done, thanks!

2023-05-10 06:17 UTC, dweinholz requested changes

2023-05-10 06:17 UTC, dweinholz commented on .github/workflows/transfer_file.yml
> +          curl -H "X-AUTH-HEADER: $API_KEY" -H "Content-Type: application/json" -X POST -d @${{ github.event.inputs.FILENAME }} "http://192.168.2.197:8080/transfer"
Please use the environment vars

2023-05-10 06:17 UTC, dweinholz commented on .github/workflows/transfer_file.yml
> +          source /home/ubuntu/.API_KEY
Please use the environment secret instead

2023-08-28 07:25 UTC, dweinholz approved these changes

2023-08-28 07:25 UTC, merged